extends GSTTestBase

## Export header block: the generator line, one notice line per included
## entry with a source_code_license, the MIT permission notice once when any
## of those is MIT, and no license claimed for the user's own stack.


func _scanned_library() -> GSTLibrary:
	var lib: GSTLibrary = GSTLibrary.new()
	lib.scan()
	return lib


func _header_block(code: String) -> Array[String]:
	var block: Array[String] = []
	for line: String in code.split("\n"):
		if line.begins_with(GSTHeader.HEADER_PREFIX):
			break
		block.append(line)
	return block


func _stack_of(entry_id: String, lib: GSTLibrary) -> GSTStack:
	var entry: GSTManifestEntry = lib.get_entry(entry_id)
	var stack: GSTStack = GSTStack.new()
	var layer: GSTLayer = GSTStackOps.add_layer(stack, entry.id, entry.kind_out, entry.coord)
	layer.manifest = entry
	return stack


func test_hash_dependency_carries_hoskins_notice_and_mit_text() -> void:
	var lib: GSTLibrary = _scanned_library()
	var code: String = GSTCodegen.generate(_stack_of("generative/value_noise", lib), lib)
	var block: Array[String] = _header_block(code)
	assert_eq(block[0], "// Generated by GoShade Turbo.", "first line names the generator only")
	assert_true(block.has("// generative/hash (hash): MIT, Copyright (c) 2014 David Hoskins"), "value_noise pulls in hash, so its notice is present: %s" % str(block))
	assert_true(block.has("// The above copyright notice and this permission notice shall be included in all"), "MIT permission notice follows the copyright lines")
	var permission_count: int = 0
	for line: String in block:
		if line.begins_with("// Permission is hereby granted"):
			permission_count += 1
	assert_eq(permission_count, 1, "the permission notice appears once")


func test_iq_ports_carry_their_notice() -> void:
	var lib: GSTLibrary = _scanned_library()
	var block: Array[String] = _header_block(GSTCodegen.generate(_stack_of("generative/cell_borders_round", lib), lib))
	assert_true(block.has("// generative/cell_borders_round (%s): MIT, Copyright (c) Inigo Quilez, iquilezles.org article code" % lib.get_entry("generative/cell_borders_round").function), "cell_borders_round notice: %s" % str(block))


func test_stack_without_third_party_code_has_generator_line_only() -> void:
	var lib: GSTLibrary = _scanned_library()
	var stack: GSTStack = GSTStack.new()
	var layer: GSTLayer = GSTStackOps.add_layer(stack, "color/fill", GSTLayer.Kind.COLOR, false)
	stack.output_color = layer.id
	var block: Array[String] = _header_block(GSTCodegen.generate(stack, lib))
	assert_eq(block, ["// Generated by GoShade Turbo."] as Array[String], "no notices, no license claim")


func test_no_export_claims_a_license_for_the_stack() -> void:
	var lib: GSTLibrary = _scanned_library()
	for id: String in lib.entries.keys():
		var entry: GSTManifestEntry = lib.get_entry(id)
		if entry.samples_source:
			continue
		var code: String = GSTCodegen.generate(_stack_of(id, lib), lib)
		assert_false(code.contains("GoShade Turbo generated shader. MIT License."), "%s export drops the old MIT stamp" % id)


func test_notices_stay_outside_the_compared_body() -> void:
	var lib: GSTLibrary = _scanned_library()
	var code: String = GSTCodegen.generate(_stack_of("generative/value_noise", lib), lib)
	var found: Dictionary = GSTOverwriteCheck.find_header_line(code)
	assert_true(found["found"], "the stack header is present")
	assert_false(String(found["body"]).contains("David Hoskins"), "notices sit above the stack line, so the overwrite check body excludes them")
