extends SceneTree

## Exports every recipe (as recipe_<stem>) and sandbox/stacks reference stack
## (as <stem>) to sandbox/mobile/shaders/ and writes
## sandbox/mobile/shader_list.gd (the stems as a const), for
## mobile_check.tscn to render on a device. Both outputs are gitignored.
## `godot --headless --path . -s res://sandbox/mobile/build_mobile_shaders.gd`

## Source folder -> output name prefix. sandbox/stacks holds files named like
## recipes, so the prefix keeps the two apart.
const SOURCES: Dictionary = {"res://addons/goshade_turbo/recipes": "recipe_", "res://sandbox/stacks": ""}
const OUT_DIR: String = "res://sandbox/mobile/shaders"
const LIST_PATH: String = "res://sandbox/mobile/shader_list.gd"


func _initialize() -> void:
	_run.call_deferred()


func _run() -> void:
	var library: GSTLibrary = GSTLibrary.new()
	library.scan()
	DirAccess.make_dir_recursive_absolute(ProjectSettings.globalize_path(OUT_DIR))
	var stems: Array[String] = []
	var failed: bool = false
	for dir: String in SOURCES:
		for file: String in DirAccess.get_files_at(dir):
			if file.get_extension() != "tres":
				continue
			var stem: String = String(SOURCES[dir]) + file.get_basename()
			if stems.has(stem):
				print("MOBILE_BUILD %s FAIL duplicate output name" % stem)
				failed = true
				continue
			var loaded: Dictionary = GSTStackIO.load(dir.path_join(file), library)
			if not loaded["ok"]:
				print("MOBILE_BUILD %s FAIL load: %s" % [stem, loaded["reason"]])
				failed = true
				continue
			var result: GSTCodegenResult = GSTExport.build(loaded["stack"], library)
			if not result.ok():
				print("MOBILE_BUILD %s FAIL codegen: %s" % [stem, result.error])
				failed = true
				continue
			var out: FileAccess = FileAccess.open(OUT_DIR.path_join(stem + ".gdshader"), FileAccess.WRITE)
			out.store_string(result.code)
			out.close()
			stems.append(stem)
	stems.sort()
	var list: FileAccess = FileAccess.open(LIST_PATH, FileAccess.WRITE)
	list.store_string("extends RefCounted\n\n## Generated by build_mobile_shaders.gd.\nconst STEMS: Array[String] = %s\n" % JSON.stringify(stems))
	list.close()
	print("MOBILE_BUILD %s %d shaders" % ["FAIL" if failed else "PASS", stems.size()])
	quit(1 if failed else 0)
